package modal;
// Generated Jan 13, 2024 10:48:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="ecom_final_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Email") 
)
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String nic;
     private String email;
     private String password;
     private Boolean active;
     private String img;
     private Set<Product> products = new HashSet<Product>(0);

    public Admin() {
    }

    public Admin(String firstName, String lastName, String nic, String email, String password, Boolean active, String img, Set<Product> products) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.nic = nic;
       this.email = email;
       this.password = password;
       this.active = active;
       this.img = img;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="First_Name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Last_Name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="Nic", length=16)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }

    
    @Column(name="Email", unique=true)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Password", length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    
    @Column(name="img", length=500)
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


