package modal;
// Generated Jan 13, 2024 10:48:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Districts generated by hbm2java
 */
@Entity
@Table(name="districts"
    ,catalog="ecom_final_db"
)
public class Districts  implements java.io.Serializable {


     private Integer id;
     private Province province;
     private String districName;
     private Set<Homecity> homecities = new HashSet<Homecity>(0);
     private Set<Postalcode> postalcodes = new HashSet<Postalcode>(0);

    public Districts() {
    }

	
    public Districts(Province province, String districName) {
        this.province = province;
        this.districName = districName;
    }
    public Districts(Province province, String districName, Set<Homecity> homecities, Set<Postalcode> postalcodes) {
       this.province = province;
       this.districName = districName;
       this.homecities = homecities;
       this.postalcodes = postalcodes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proince_id", nullable=false)
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }

    
    @Column(name="distric_name", nullable=false, length=45)
    public String getDistricName() {
        return this.districName;
    }
    
    public void setDistricName(String districName) {
        this.districName = districName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="districts")
    public Set<Homecity> getHomecities() {
        return this.homecities;
    }
    
    public void setHomecities(Set<Homecity> homecities) {
        this.homecities = homecities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="districts")
    public Set<Postalcode> getPostalcodes() {
        return this.postalcodes;
    }
    
    public void setPostalcodes(Set<Postalcode> postalcodes) {
        this.postalcodes = postalcodes;
    }




}


