package modal;
// Generated Dec 26, 2023 2:34:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MainCategory generated by hbm2java
 */
@Entity
@Table(name="main_category"
    ,catalog="ecom_final_db"
)
public class MainCategory  implements java.io.Serializable {


     private Integer MId;
     private String description;
     private Set<SubCategory> subCategories = new HashSet<SubCategory>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public MainCategory() {
    }

	
    public MainCategory(String description) {
        this.description = description;
    }
    public MainCategory(String description, Set<SubCategory> subCategories, Set<Product> products) {
       this.description = description;
       this.subCategories = subCategories;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="m_id", unique=true, nullable=false)
    public Integer getMId() {
        return this.MId;
    }
    
    public void setMId(Integer MId) {
        this.MId = MId;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mainCategory")
    public Set<SubCategory> getSubCategories() {
        return this.subCategories;
    }
    
    public void setSubCategories(Set<SubCategory> subCategories) {
        this.subCategories = subCategories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mainCategory")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


