package modal;
// Generated Dec 26, 2023 2:34:59 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Postalcode generated by hbm2java
 */
@Entity
@Table(name="postalcode"
    ,catalog="ecom_final_db"
)
public class Postalcode  implements java.io.Serializable {


     private Integer id;
     private Districts districts;
     private String areaName;
     private String districtCode;
     private int postalcode;

    public Postalcode() {
    }

    public Postalcode(Districts districts, String areaName, String districtCode, int postalcode) {
       this.districts = districts;
       this.areaName = areaName;
       this.districtCode = districtCode;
       this.postalcode = postalcode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id", nullable=false)
    public Districts getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Districts districts) {
        this.districts = districts;
    }

    
    @Column(name="Area_name", nullable=false, length=45)
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    
    @Column(name="district_code", nullable=false, length=45)
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    
    @Column(name="postalcode", nullable=false)
    public int getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(int postalcode) {
        this.postalcode = postalcode;
    }




}


