package modal;
// Generated Dec 26, 2023 2:34:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name="province"
    ,catalog="ecom_final_db"
)
public class Province  implements java.io.Serializable {


     private Integer id;
     private String province;
     private Set<Districts> districtses = new HashSet<Districts>(0);

    public Province() {
    }

	
    public Province(String province) {
        this.province = province;
    }
    public Province(String province, Set<Districts> districtses) {
       this.province = province;
       this.districtses = districtses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="province", nullable=false, length=45)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="province")
    public Set<Districts> getDistrictses() {
        return this.districtses;
    }
    
    public void setDistrictses(Set<Districts> districtses) {
        this.districtses = districtses;
    }




}


