package modal;
// Generated Dec 20, 2023 2:24:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShippingAddress generated by hbm2java
 */
@Entity
@Table(name="shipping_address"
    ,catalog="ecom_final_db"
)
public class ShippingAddress  implements java.io.Serializable {


     private int id;
     private UserLogin userLogin;
     private String mainCity;
     private String homeCity;
     private String addressLine1;
     private String addressLine2;
     private String shippingAddresscol;
     private String postalCode;
     private boolean isactive;

    public ShippingAddress() {
    }

    public ShippingAddress(int id, UserLogin userLogin, String mainCity, String homeCity, String addressLine1, String addressLine2, String shippingAddresscol, String postalCode, boolean isactive) {
       this.id = id;
       this.userLogin = userLogin;
       this.mainCity = mainCity;
       this.homeCity = homeCity;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.shippingAddresscol = shippingAddresscol;
       this.postalCode = postalCode;
       this.isactive = isactive;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

    
    @Column(name="main_city", nullable=false, length=20)
    public String getMainCity() {
        return this.mainCity;
    }
    
    public void setMainCity(String mainCity) {
        this.mainCity = mainCity;
    }

    
    @Column(name="home_city", nullable=false, length=20)
    public String getHomeCity() {
        return this.homeCity;
    }
    
    public void setHomeCity(String homeCity) {
        this.homeCity = homeCity;
    }

    
    @Column(name="address_line1", nullable=false, length=45)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line2", nullable=false, length=45)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="shipping_addresscol", nullable=false, length=45)
    public String getShippingAddresscol() {
        return this.shippingAddresscol;
    }
    
    public void setShippingAddresscol(String shippingAddresscol) {
        this.shippingAddresscol = shippingAddresscol;
    }

    
    @Column(name="postal_code", nullable=false, length=45)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="isactive", nullable=false)
    public boolean isIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }




}


