package modal;
// Generated Jan 13, 2024 10:48:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StockVisibility generated by hbm2java
 */
@Entity
@Table(name="stock_visibility"
    ,catalog="ecom_final_db"
)
public class StockVisibility  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Integer stockVisibility;

    public StockVisibility() {
    }

	
    public StockVisibility(Product product) {
        this.product = product;
    }
    public StockVisibility(Product product, Integer stockVisibility) {
       this.product = product;
       this.stockVisibility = stockVisibility;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="stock_visibility")
    public Integer getStockVisibility() {
        return this.stockVisibility;
    }
    
    public void setStockVisibility(Integer stockVisibility) {
        this.stockVisibility = stockVisibility;
    }




}


