package modal;
// Generated Jan 13, 2024 10:48:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name="sub_category"
    ,catalog="ecom_final_db"
)
public class SubCategory  implements java.io.Serializable {


     private Integer SId;
     private MainCategory mainCategory;
     private String description;
     private Set<Product> products = new HashSet<Product>(0);
     private Set<Category> categories = new HashSet<Category>(0);

    public SubCategory() {
    }

	
    public SubCategory(MainCategory mainCategory, String description) {
        this.mainCategory = mainCategory;
        this.description = description;
    }
    public SubCategory(MainCategory mainCategory, String description, Set<Product> products, Set<Category> categories) {
       this.mainCategory = mainCategory;
       this.description = description;
       this.products = products;
       this.categories = categories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="s_id", unique=true, nullable=false)
    public Integer getSId() {
        return this.SId;
    }
    
    public void setSId(Integer SId) {
        this.SId = SId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="m_id", nullable=false)
    public MainCategory getMainCategory() {
        return this.mainCategory;
    }
    
    public void setMainCategory(MainCategory mainCategory) {
        this.mainCategory = mainCategory;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }




}


