package modal;
// Generated Dec 20, 2023 6:59:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRegistration generated by hbm2java
 */
@Entity
@Table(name="user_registration"
    ,catalog="ecom_final_db"
)
public class UserRegistration  implements java.io.Serializable {


     private Integer id;
     private UserLogin userLogin;
     private String fullName;
     private Date dob;
     private String gender;
     private Date addtoby;
     private String email;
     private String mobileNo;
     private String mainCity;
     private String homeCity;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private String postalCode;
     private boolean isactive;

    public UserRegistration() {
    }

    public UserRegistration(UserLogin userLogin, String fullName, Date dob, String gender, Date addtoby, String email, String mobileNo, String mainCity, String homeCity, String addressLine1, String addressLine2, String addressLine3, String postalCode, boolean isactive) {
       this.userLogin = userLogin;
       this.fullName = fullName;
       this.dob = dob;
       this.gender = gender;
       this.addtoby = addtoby;
       this.email = email;
       this.mobileNo = mobileNo;
       this.mainCity = mainCity;
       this.homeCity = homeCity;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.postalCode = postalCode;
       this.isactive = isactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }

    
    @Column(name="full_name", nullable=false, length=100)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", nullable=false, length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="Gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="addtoby", nullable=false, length=19)
    public Date getAddtoby() {
        return this.addtoby;
    }
    
    public void setAddtoby(Date addtoby) {
        this.addtoby = addtoby;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobile_no", nullable=false, length=15)
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    
    @Column(name="main_city", nullable=false, length=45)
    public String getMainCity() {
        return this.mainCity;
    }
    
    public void setMainCity(String mainCity) {
        this.mainCity = mainCity;
    }

    
    @Column(name="home_city", nullable=false, length=45)
    public String getHomeCity() {
        return this.homeCity;
    }
    
    public void setHomeCity(String homeCity) {
        this.homeCity = homeCity;
    }

    
    @Column(name="address_line1", nullable=false, length=45)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line2", nullable=false, length=45)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="address_line3", nullable=false, length=45)
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }

    
    @Column(name="postal_code", nullable=false, length=45)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="isactive", nullable=false)
    public boolean isIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }




}


