package modal;
// Generated Jan 13, 2024 10:48:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name="user_login"
    ,catalog="ecom_final_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Email") 
)
public class UserLogin  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private String hash;
     private Boolean active;
     private String userImg;
     private Set<UserRegistration> userRegistrations = new HashSet<UserRegistration>(0);
     private Set<ShippingAddress> shippingAddresses = new HashSet<ShippingAddress>(0);

    public UserLogin() {
    }

    public UserLogin(String firstName, String lastName, String email, String password, String hash, Boolean active, String userImg, Set<UserRegistration> userRegistrations, Set<ShippingAddress> shippingAddresses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.hash = hash;
       this.active = active;
       this.userImg = userImg;
       this.userRegistrations = userRegistrations;
       this.shippingAddresses = shippingAddresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="First_Name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Last_Name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="Email", unique=true)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Hash")
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }

    
    @Column(name="Active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    
    @Column(name="user_img", length=500)
    public String getUserImg() {
        return this.userImg;
    }
    
    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<UserRegistration> getUserRegistrations() {
        return this.userRegistrations;
    }
    
    public void setUserRegistrations(Set<UserRegistration> userRegistrations) {
        this.userRegistrations = userRegistrations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userLogin")
    public Set<ShippingAddress> getShippingAddresses() {
        return this.shippingAddresses;
    }
    
    public void setShippingAddresses(Set<ShippingAddress> shippingAddresses) {
        this.shippingAddresses = shippingAddresses;
    }




}


